name: CICD
on:
  workflow_dispatch:
  push:
    branches: main
  pull_request:
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: clone the repository
        uses: actions/checkout@v4.1.2
      - name: setup java version
        uses: actions/setup-java@4.2.1
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build Project
        run: mvn package
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker image build and run
        run: |
          docker build -t myapp:latest
          docker images
          docker run -dt-name web1 myapp:latest
        
